services:
  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: mesh-college
    ports:
      - "8000:8000"
    volumes:
      - ../backend/data:/app/backend/data:rw
      - ../uploads:/app/uploads:rw
    restart: unless-stopped
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN:-1111}